import { SwaggerOptions } from "swagger-ui-express";
import swaggerJsdoc from "swagger-jsdoc";
import config from "../src/config";

const swaggerOptions: SwaggerOptions = {
	definition: {
		openapi: "3.0.0",
		info: {
			title: "Task Manager API Documentation",
			version: "1.0.0",
			description: "Express API with autogenerated Swagger documentation",
		},
		servers: [
			{
				url: config.URL,
			},
		],
	},
	apis: ["./src/api/routes/*.ts", "./src/data/models/*.ts"],
	tags: [
		{
			name: "Tasks",
			description: "Operations related to task management",
		},
		{
			name: "Projects",
			description: "Operations related to project management",
		},
		{
			name: "Users",
			description: "Operations related to user management",
		},
		{
			name: "Auth",
			description: "Operations related to authentication",
		},
	],
};

const swaggerSpec = swaggerJsdoc(swaggerOptions);

export default swaggerSpec;
